using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata.Conventions;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Amazon.AuroraDsql.EntityFrameworkCore.Metadata;

/// <summary>
/// Applies DSQL-compatible key defaults: <c>gen_random_uuid()</c> for <see cref="Guid" /> primary
/// keys, and widens <see cref="int" /> identity keys to <c>bigint</c> (DSQL only supports
/// <c>bigint</c> identity columns). Existing explicit configuration is left untouched.
/// </summary>
/// <remarks>
/// Identity cache sizing is handled by the migrations SQL generator rather than here: annotations
/// added in a model-finalizing convention do not survive into the runtime model (verified against
/// EF Core 10 / Npgsql EF 10). See <c>docs/implementation-plan.md</c> Phase 3.
/// </remarks>
internal sealed class DsqlModelFinalizingConvention : IModelFinalizingConvention
{
    public void ProcessModelFinalizing(
        IConventionModelBuilder modelBuilder,
        IConventionContext<IConventionModelBuilder> context)
    {
        foreach (var entityType in modelBuilder.Metadata.GetEntityTypes())
        {
            var primaryKey = entityType.FindPrimaryKey();
            if (primaryKey is null)
            {
                continue;
            }

            foreach (var property in primaryKey.Properties)
            {
                ConfigureKeyProperty(property);
            }
        }
    }

    private static void ConfigureKeyProperty(IConventionProperty property)
    {
        if (property.GetDefaultValueSql() is not null)
        {
            return;
        }

        var strategy = property.GetValueGenerationStrategy();

        if (property.ClrType == typeof(Guid))
        {
            if (strategy != NpgsqlValueGenerationStrategy.None)
            {
                return;
            }

            property.Builder.HasDefaultValueSql("gen_random_uuid()");
            property.Builder.ValueGenerated(ValueGenerated.OnAdd);
            return;
        }

        // DSQL only supports bigint identity columns. An int key generated by identity is widened to
        // bigint (with a converter) so the model keeps its int property.
        if (property.ClrType == typeof(int)
            && strategy is NpgsqlValueGenerationStrategy.IdentityAlwaysColumn
                or NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
        {
            property.SetValueConverter(new ValueConverter<int, long>(value => value, value => checked((int)value)));
            property.Builder.HasColumnType("bigint");
        }
    }
}
