using Amazon.AuroraDsql.EntityFrameworkCore.Extensions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Migrations.Operations;
using Npgsql;
using NpgsqlValueGenerationStrategy = Npgsql.EntityFrameworkCore.PostgreSQL.Metadata.NpgsqlValueGenerationStrategy;

namespace Amazon.AuroraDsql.EntityFrameworkCore.Tests.Migrations;

public class DsqlMigrationsSqlGeneratorTests : IDisposable
{
    private readonly NpgsqlDataSource _dataSource =
        new NpgsqlDataSourceBuilder("Host=localhost;Username=admin;Database=postgres").Build();

    public void Dispose() => _dataSource.Dispose();

    private sealed class MigrationsContext : DbContext
    {
        public MigrationsContext(DbContextOptions<MigrationsContext> options)
            : base(options)
        {
        }

        public DbSet<Widget> Widgets => Set<Widget>();
    }

    private sealed class Widget
    {
        public Guid Id { get; set; }
        public string Name { get; set; } = string.Empty;
        public int Quantity { get; set; }
    }

    private MigrationsContext CreateContext()
    {
        var options = new DbContextOptionsBuilder<MigrationsContext>()
            .UseDsql(_dataSource, dsql => dsql.EnableIdentityColumns())
            .Options;

        return new MigrationsContext(options);
    }

    private static IReadOnlyList<MigrationCommand> Generate(MigrationsContext context, params MigrationOperation[] operations)
        => context.GetService<IMigrationsSqlGenerator>().Generate(operations, context.Model);

    [Fact]
    public void Create_index_uses_async()
    {
        using var context = CreateContext();

        var commands = Generate(
            context,
            new CreateIndexOperation
            {
                Name = "IX_Widgets_Name",
                Table = "Widgets",
                Columns = ["Name"],
            });

        var sql = string.Join("\n", commands.Select(c => c.CommandText));
        Assert.Contains("CREATE INDEX ASYNC", sql);
    }

    [Fact]
    public void Unique_index_uses_async()
    {
        using var context = CreateContext();

        var commands = Generate(
            context,
            new CreateIndexOperation
            {
                Name = "IX_Widgets_Name",
                Table = "Widgets",
                Columns = ["Name"],
                IsUnique = true,
            });

        var sql = string.Join("\n", commands.Select(c => c.CommandText));
        Assert.Contains("CREATE UNIQUE INDEX ASYNC", sql);
    }

    private static CreateTableOperation IdentityTable()
    {
        var operation = new CreateTableOperation { Name = "Widgets" };
        operation.Columns.Add(new AddColumnOperation
        {
            Name = "Id",
            Table = "Widgets",
            ClrType = typeof(long),
            ColumnType = "bigint",
            IsNullable = false,
        });
        operation.Columns[0]["Npgsql:ValueGenerationStrategy"] =
            NpgsqlValueGenerationStrategy.IdentityByDefaultColumn;
        operation.PrimaryKey = new AddPrimaryKeyOperation
        {
            Name = "PK_Widgets",
            Table = "Widgets",
            Columns = ["Id"],
        };

        return operation;
    }

    [Fact]
    public void Identity_column_gets_cache_when_enabled()
    {
        using var context = CreateContext();

        var commands = Generate(context, IdentityTable());
        var sql = string.Join("\n", commands.Select(c => c.CommandText));

        Assert.Contains("GENERATED BY DEFAULT AS IDENTITY", sql);
        Assert.Contains("CACHE 65536", sql);
    }

    [Fact]
    public void Identity_column_gets_cache_one_when_not_enabled()
    {
        var options = new DbContextOptionsBuilder<MigrationsContext>().UseDsql(_dataSource).Options;
        using var context = new MigrationsContext(options);

        var commands = Generate(context, IdentityTable());
        var sql = string.Join("\n", commands.Select(c => c.CommandText));

        // DSQL requires an explicit cache; CACHE 1 is the non-caching default.
        Assert.Contains("GENERATED BY DEFAULT AS IDENTITY", sql);
        Assert.Contains("CACHE 1", sql);
    }

    [Fact]
    public void Add_foreign_key_is_not_valid_then_validated_async()
    {
        using var context = CreateContext();

        var commands = Generate(
            context,
            new AddForeignKeyOperation
            {
                Name = "FK_Widgets_Owners_OwnerId",
                Table = "Widgets",
                Columns = ["OwnerId"],
                PrincipalTable = "Owners",
                PrincipalColumns = ["Id"],
            });

        var sql = string.Join("\n", commands.Select(c => c.CommandText));

        Assert.Contains("NOT VALID", sql);
        Assert.Contains("ALTER TABLE ASYNC", sql);
        Assert.Contains("VALIDATE CONSTRAINT", sql);
    }

    [Fact]
    public void Inline_foreign_key_in_create_table_is_not_marked_not_valid()
    {
        using var context = CreateContext();

        var operation = new CreateTableOperation { Name = "Widgets" };
        operation.Columns.Add(new AddColumnOperation
        {
            Name = "Id",
            Table = "Widgets",
            ClrType = typeof(Guid),
            ColumnType = "uuid",
            IsNullable = false,
        });
        operation.PrimaryKey = new AddPrimaryKeyOperation
        {
            Name = "PK_Widgets",
            Table = "Widgets",
            Columns = ["Id"],
        };
        operation.ForeignKeys.Add(new AddForeignKeyOperation
        {
            Name = "FK_Widgets_Owners_OwnerId",
            Table = "Widgets",
            Columns = ["Id"],
            PrincipalTable = "Owners",
            PrincipalColumns = ["Id"],
        });

        var commands = Generate(context, operation);
        var sql = string.Join("\n", commands.Select(c => c.CommandText));

        Assert.Contains("FOREIGN KEY", sql);
        Assert.DoesNotContain("NOT VALID", sql);
    }

    [Fact]
    public void Alter_column_type_is_rejected()
    {
        using var context = CreateContext();

        var operation = new AlterColumnOperation
        {
            Name = "Quantity",
            Table = "Widgets",
            ClrType = typeof(long),
            ColumnType = "bigint",
            OldColumn = new AddColumnOperation { ClrType = typeof(int), ColumnType = "integer" },
        };

        var exception = Assert.Throws<InvalidOperationException>(() => Generate(context, operation));
        Assert.Contains("ALTER COLUMN", exception.Message);
    }

    [Fact]
    public void Create_table_is_idempotent()
    {
        using var context = CreateContext();

        var sql = string.Join("\n", Generate(context, IdentityTable()).Select(c => c.CommandText));

        Assert.Contains("CREATE TABLE IF NOT EXISTS", sql);
    }

    [Fact]
    public void Create_index_is_idempotent()
    {
        using var context = CreateContext();

        var commands = Generate(
            context,
            new CreateIndexOperation { Name = "IX_Widgets_Name", Table = "Widgets", Columns = ["Name"] });

        Assert.Contains("CREATE INDEX ASYNC IF NOT EXISTS", string.Join("\n", commands.Select(c => c.CommandText)));
    }

    [Fact]
    public void Add_column_is_idempotent()
    {
        using var context = CreateContext();

        var commands = Generate(
            context,
            new AddColumnOperation
            {
                Name = "Extra",
                Table = "Widgets",
                ClrType = typeof(string),
                ColumnType = "text",
                IsNullable = true,
            });

        Assert.Contains("ADD COLUMN IF NOT EXISTS", string.Join("\n", commands.Select(c => c.CommandText)));
    }

    [Fact]
    public void Drops_are_idempotent()
    {
        using var context = CreateContext();

        var drops = string.Join(
            "\n",
            Generate(context, new DropTableOperation { Name = "Widgets" }).Select(c => c.CommandText));
        Assert.Contains("DROP TABLE IF EXISTS", drops);

        drops = string.Join(
            "\n",
            Generate(context, new DropIndexOperation { Name = "IX_Widgets_Name", Table = "Widgets" })
                .Select(c => c.CommandText));
        Assert.Contains("DROP INDEX IF EXISTS", drops);

        drops = string.Join(
            "\n",
            Generate(context, new DropColumnOperation { Name = "Quantity", Table = "Widgets" })
                .Select(c => c.CommandText));
        Assert.Contains("DROP COLUMN IF EXISTS", drops);

        drops = string.Join(
            "\n",
            Generate(context, new DropForeignKeyOperation { Name = "FK_Widgets_Owners_OwnerId", Table = "Widgets" })
                .Select(c => c.CommandText));
        Assert.Contains("DROP CONSTRAINT IF EXISTS", drops);
    }

    [Fact]
    public void Create_schema_is_idempotent()
    {
        using var context = CreateContext();

        var commands = Generate(context, new EnsureSchemaOperation { Name = "myschema" });

        Assert.Contains("CREATE SCHEMA IF NOT EXISTS", string.Join("\n", commands.Select(c => c.CommandText)));
    }

    [Fact]
    public void Add_check_constraint_is_not_valid()
    {
        using var context = CreateContext();

        var commands = Generate(
            context,
            new AddCheckConstraintOperation
            {
                Name = "CK_Widgets_Quantity",
                Table = "Widgets",
                Sql = "\"Quantity\" >= 0",
            });

        Assert.Contains("NOT VALID", string.Join("\n", commands.Select(c => c.CommandText)));
    }

    [Fact]
    public void Add_primary_key_to_existing_table_is_rejected()
    {
        using var context = CreateContext();

        var operation = new AddPrimaryKeyOperation
        {
            Name = "PK_Widgets",
            Table = "Widgets",
            Columns = ["Id"],
        };

        var exception = Assert.Throws<InvalidOperationException>(() => Generate(context, operation));
        Assert.Contains("PRIMARY KEY", exception.Message);
    }

    [Fact]
    public void Table_comment_is_rejected()
    {
        using var context = CreateContext();

        var operation = IdentityTable();
        operation.Comment = "widgets";

        var exception = Assert.Throws<InvalidOperationException>(() => Generate(context, operation));
        Assert.Contains("comment", exception.Message, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public void Concurrent_index_is_rejected()
    {
        using var context = CreateContext();

        var operation = new CreateIndexOperation
        {
            Name = "IX_Widgets_Name",
            Table = "Widgets",
            Columns = ["Name"],
        };
        operation["Npgsql:CreatedConcurrently"] = true;

        var exception = Assert.Throws<InvalidOperationException>(() => Generate(context, operation));
        Assert.Contains("CONCURRENTLY", exception.Message);
    }
}
