#!/usr/bin/env python3
"""Adapt efcore.pg's Northwind.sql for Aurora DSQL.

- drops SET / CREATE EXTENSION / trigger toggles / collation
- SERIAL -> INTEGER GENERATED BY DEFAULT AS IDENTITY (CACHE 1)
- CREATE INDEX -> CREATE INDEX ASYNC <name> (unique synthetic names)
- materialises the two views the tests use as tables + INSERT..SELECT, drops the rest
- ALTER TABLE ADD CONSTRAINT ... FOREIGN KEY -> NOT VALID + ALTER TABLE ASYNC VALIDATE
- batches single-row INSERTs into multi-row INSERTs (same data, ~100x fewer round trips)
- emits statements separated by GO lines (reuses the harness ExecuteScript splitter)
"""
import re
import sys

src, dst = sys.argv[1], sys.argv[2]
text = open(src, encoding="utf-8", errors="replace").read()
# Drop line comments so they cannot glue two statements together (they are not inside data).
text = "\n".join(l for l in text.splitlines() if not l.lstrip().startswith("--"))

# Statements are separated by lines containing only GO (case-insensitive).
chunks = re.split(r"(?im)^\s*GO\s*$", text)


def split_semicolons(chunk: str):
    """Quote-aware split on ';' (handles '...' and E'...' with doubled quotes)."""
    out, buf, i, n = [], [], 0, len(chunk)
    quote = None
    while i < n:
        c = chunk[i]
        if quote:
            buf.append(c)
            if c == quote:
                if i + 1 < n and chunk[i + 1] == quote:  # doubled quote
                    buf.append(chunk[i + 1]); i += 2; continue
                quote = None
            i += 1
            continue
        if c == "'":
            quote = "'"; buf.append(c); i += 1; continue
        if c == ";":
            out.append("".join(buf).strip()); buf = []; i += 1; continue
        buf.append(c); i += 1
    if "".join(buf).strip():
        out.append("".join(buf).strip())
    return out


statements = []
for chunk in chunks:
    chunk = chunk.strip()
    if not chunk:
        continue
    if re.search(r"\bLANGUAGE\s+SQL\b", chunk, re.I):
        chunk = re.sub(r'date_part\("([a-z]+)"\s*,', r"date_part(''\1'',", chunk, flags=re.I)
        statements.append(chunk)          # keep the whole function
    else:
        statements.extend(split_semicolons(chunk))

DROP_VIEWS = {
    '"Category Sales for 1997"', '"Sales by Category"', '"Sales Totals by Amount"',
    '"Summary of Sales by Quarter"', '"Summary of Sales by Year"',
}
out = []
deferred = []
inserts: dict = {}
insert_order: list = []
index_seq = 0

_insert_re = re.compile(
    r'^insert\s+into\s+(?P<table>"(?:[^"]|"")*"|\S+)\s*(?:\((?P<cols>[^)]*)\))?\s*values\s*(?P<row>.+)$',
    re.I | re.S)

# DSQL does not support adding a PRIMARY KEY with ALTER TABLE. Collect those and fold them into the
# table's CREATE TABLE instead (the CREATE TABLE appears earlier in the script).
pk_re = re.compile(
    r'alter\s+table\s+("(?:[^"]|"")*"|\S+)\s+add\s+constraint\s+("(?:[^"]|"")*"|\S+)\s+primary\s+key\s*\(([^)]*)\)',
    re.I | re.S)
pk_by_table = {}
for _stmt in statements:
    _m = pk_re.match(_stmt.strip())
    if _m:
        pk_by_table[_m.group(1).strip()] = (_m.group(2).strip(), _m.group(3).strip())

for stmt in statements:
    s = re.sub(r"^(?:\s*--[^\n]*\n)+", "", stmt.strip()).strip()
    if not s:
        continue
    low = s.lower()

    # SERIAL -> bigint identity: Aurora DSQL only supports bigint identity columns (the provider
    # widens the model's int keys to bigint to match). BY DEFAULT keeps explicit inserts working.
    s = re.sub(r'\b(BIG|SMALL)?SERIAL\b', 'BIGINT GENERATED BY DEFAULT AS IDENTITY (CACHE 1)', s, flags=re.I)

    if low.startswith(("set ", "create extension", "grant ", "revoke ")):
        continue
    if "disable trigger" in low or "enable trigger" in low:
        continue
    if "create collation" in low:
        continue

    # Views: materialise the two the tests use, drop the rest.
    m = re.match(r'create\s+(or\s+replace\s+)?view\s+("(?:[^"]|"")*"|\S+)\s+as\s+(.*)', s, re.I | re.S)
    if m:
        name = m.group(2).strip()
        body = m.group(3).strip()
        if name == '"Order Subtotals"':
            out.append('CREATE TABLE "Order Subtotals" ("OrderID" integer NOT NULL, "Subtotal" numeric(12,2) NULL, CONSTRAINT "PK_Order_Subtotals" PRIMARY KEY ("OrderID"))')
            # Populate after all data is inserted (deferred to the end).
            deferred.append('INSERT INTO "Order Subtotals" ("OrderID", "Subtotal") ' + body)
        elif name == '"Product Sales for 1997"':
            out.append('CREATE TABLE "Product Sales for 1997" ("CategoryName" character varying(15) NULL, "ProductName" character varying(40) NULL, "ProductSales" numeric(12,2) NULL)')
            deferred.append('INSERT INTO "Product Sales for 1997" ("CategoryName", "ProductName", "ProductSales") ' + body)
        else:
            continue
        continue

    # Move foreign keys out of CREATE TABLE so they can be added after the data load
    # (the original script disables triggers during the load, which DSQL does not support).
    if low.startswith("create table"):
        open_paren = s.index("(")
        close_paren = s.rindex(")")
        table = s[len("create table"):open_paren].strip()
        body = s[open_paren + 1:close_paren]
        fk_re = re.compile(
            r'CONSTRAINT\s+("(?:[^"]|"")*")\s+FOREIGN\s+KEY\s*\(([^)]*)\)\s*'
            r'REFERENCES\s+("(?:[^"]|"")*")\s*\(([^)]*)\)'
            r'((?:\s+ON\s+(?:DELETE|UPDATE)\s+(?:NO\s+ACTION|RESTRICT|CASCADE|SET\s+NULL|SET\s+DEFAULT))*)',
            re.I | re.S)
        found = []
        def take(m):
            found.append(m)
            return ""
        body = fk_re.sub(take, body)
        # Removing FKs can leave runs of commas (also mid-body if a CHECK follows).
        body = re.sub(r",(?:\s*,)+", ",", body)
        body = re.sub(r"[,\s]+$", "", body)

        if table in pk_by_table:
            (pk_name, pk_cols) = pk_by_table[table]
            body = body.rstrip() + f",\n\tCONSTRAINT {pk_name} PRIMARY KEY ({pk_cols})"
        for m in found:
            name, cols, ref_table, ref_cols, actions = (
                m.group(1), m.group(2).strip(), m.group(3), m.group(4).strip(), m.group(5).strip())
            deferred.append(f'ALTER TABLE {table} ADD CONSTRAINT {name} FOREIGN KEY ({cols}) REFERENCES {ref_table} ({ref_cols}){(" " + actions) if actions else ""} NOT VALID')
        out.append(f'CREATE TABLE {table} ({body})')
        continue

    # Secondary indexes are skipped: DSQL's CREATE INDEX ASYNC runs in the background, and an
    # in-progress build conflicts with the data load (OC001). Query tests do not need them.
    if re.match(r'create\s+(unique\s+)?index\s+on\s+', s, re.I):
        continue

    # DSQL does not support adding a PRIMARY KEY via ALTER TABLE; skip those (query tests do not
    # need them).
    if re.match(r'alter\s+table\s+\S+\s+add\s+constraint\s+\S+\s+primary\s+key', s, re.I):
        continue

    # Foreign keys added to existing tables need NOT VALID + async validation.
    m = re.match(r'alter\s+table\s+("(?:[^"]|"")*"|\S+)\s+add\s+constraint\s+("(?:[^"]|"")*"|\S+)\s+foreign\s+key', s, re.I | re.S)
    if m:
        # Defer to after every insert: a NOT VALID foreign key is still enforced for new rows, and
        # with subsampled data some child rows reference parents that were dropped.
        deferred.append(s.rstrip(";") + " NOT VALID")
        continue

    m = _insert_re.match(s)
    if m:
        table = m.group("table")
        if table not in inserts:
            inserts[table] = (m.group("cols") or "", [])
            insert_order.append(table)
        inserts[table][1].append(m.group("row").strip().rstrip(";").strip())
        continue

    out.append(s)

# Emit the full dataset as batched multi-row INSERTs (DSQL supports a VALUES list), keeping the
# number of round trips small over the WAN.
_batch = 250
for _table in insert_order:
    _cols, _rows = inserts[_table]
    for _start in range(0, len(_rows), _batch):
        _chunk = _rows[_start:_start + _batch]
        _target = f'{_table} ({_cols})' if _cols else _table
        out.append("INSERT INTO " + _target + " VALUES\n" + ",\n".join(_chunk))

out.extend(deferred)
open(dst, "w", encoding="utf-8").write("\nGO\n".join(out) + "\nGO\n")
print(f"statements: {len(out)}")
